apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: hooker
build:
  artifacts:
  - image: samlockart/hooker
    kaniko:
      cache: {}
  cluster:
    pullSecretName: kaniko-secret
    namespace: build
deploy:
  kubectl:
    manifests:
    - k8s-*
